name:                mimizuku
version:             0.1.0.0
github:              "matsumonkie/mimizuku"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

default-extensions:
  - LambdaCase
  - OverloadedStrings
  - NamedFieldPuns
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - RecordWildCards
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - InstanceSigs
  - MultiParamTypeClasses
  - MultiWayIf
  - StrictData
  - TypeApplications # allows you to use visible type application in expressions, eg: show (read @Int "5")

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HieParser#readme>

ghc-options:
  - -Wall
  - -fno-warn-name-shadowing
  - -Wincomplete-patterns
  - -Wcompat # make code future compatible to adapt to new features
  - -Wincomplete-record-updates # catch what are essentially partial pattern-matches
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints # help remove unnecessary typeclass constraints on functions
  - -fwrite-ide-info
  - -hiedir=.hie

dependencies:
- algebraic-graphs
- base >= 4.7 && < 5
- bytestring
- containers
- dhall
- directory
- filepath
- generic-lens
- ghc
- lens
- mtl
- optparse-applicative
- regex-tdfa
- servant-server
- servant-flatten
- wai-cors
- stm
- text
- transformers
- foreign-store
- safe-exceptions
- say
- utf8-string
- wai
- warp
- case-insensitive
- http-types
- aeson
- array
- ghc-paths
- pretty-simple
- directory

library:
  source-dirs: src

executables:
  mimizuku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimizuku

tests:
  spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mimizuku
    - hspec
    - servant-client
